### ISSUE TITLE
Helplink pointing to wrong location

### ISSUE THREAD

**Issue by JohanLarsson** [DotNetAnalyzers/PublicApiAnalyzer#22]
Clicking in the error list navigates to:
https://github.com/DotNetAnalyzers/PublicApiAnalyzer/blob/master/documentation/RS0026.md

**Comment by sharwell** [comment]
It should probably point to https://github.com/DotNetAnalyzers/PublicApiAnalyzer/blob/master/docs/RS0026.md, but the main issue right now is there are no docs to point to.

**Comment by JohanLarsson** [comment]
I use this hack for testing that docs exists and for generating stubs. Not pretty but have worked well enough. Can PR it if you want it.
